# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/users.json
Users:
  - Name: Berta
    FullName: Berta Meier
  - Name: Anna
    Password: anna.123
    FullName: Anna Sunshine
    Mail: anna@sunshine.com
    Roles:
      - Secretary
    Properties:
      phone: 0123 456 789
      office: LONDON
